# Generated by Django 3.1.3 on 2020-11-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='renthouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housetype', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('room', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('available', models.DateTimeField()),
                ('img', models.ImageField(upload_to='pics')),
                ('disc', models.TextField()),
                ('post_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
