# Generated by Django 3.1.3 on 2020-11-27 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentrent', '0002_favorite_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='housebooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renter_name', models.CharField(max_length=100)),
                ('cardholder_name', models.CharField(max_length=100)),
                ('cardnumber', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('cvc', models.CharField(max_length=3)),
                ('email', models.EmailField(max_length=254)),
                ('renthouseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentrent.renthouse')),
            ],
        ),
    ]
