# Generated by Django 3.1.3 on 2020-11-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentrent', '0003_housebooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housebooking',
            name='renthouseid',
            field=models.CharField(max_length=100),
        ),
    ]
